### PR TITLE
[REVIEW] Add Python 3.8 support

### PR DESCRIPTION
**Pull request by raydouglass**

### CODE REVIEW

**Comment by raydouglass** [comment]
rerun tests

**Comment by raydouglass** [comment]
> Should we also enable Python 3.8 for `ucx-py`'s CI?

This PR should do that. The edited files are added in as variants during the conda build.

**Comment by jakirkham** [comment]
Sorry I meant the `ucx-py` source.

**Comment by jakirkham** [comment]
Adding the corresponding migration file in PR ( https://github.com/rapidsai/ucx-split-feedstock/pull/31 ) to ensure `conda smithy rerender` will keep Python 3.8 in the build matrix.

**Pull request merged**
