### PR TITLE
[WIP] ENH Enable CPU build

### PR DESCRIPTION
**Pull request by mike-wendt**
Enable CPU-only build for UCX

### CODE REVIEW

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
@jakirkham so I have the gpuCI side of things in place to support CPU only; however, from the above runs we don't build the `ucx-py` CPU version

see:
- master branch - https://gpuci.gpuopenanalytics.com/job/rapidsai/job/conda/job/ucx/job/ucx-py-prb-release/41/CONDA_USERNAME=rapidsai,CUDA_VER=None,FROM_IMAGE=condaforge%2Flinux-anvil-comp7,UCX_COMMIT=v1.8.x,UCX_PROC_VER=1.0.0,UCX_PY_COMMIT=master,UCX_VER=1.8.0dev/console#L2,794
- branch-0.14 - https://gpuci.gpuopenanalytics.com/job/rapidsai/job/conda/job/ucx/job/ucx-py-prb-nightly/CONDA_USERNAME=rapidsai-nightly,CUDA_VER=None,FROM_IMAGE=condaforge%2Flinux-anvil-comp7,UCX_COMMIT=v1.8.x,UCX_PROC_VER=1.0.0,UCX_PY_COMMIT=branch-0.14,UCX_VER=1.8.0dev/41/consoleFull#L2,805

Can you help update the meta.yaml and config to support this? You should be able to use the testing here to debug

**Comment by jakirkham** [comment]
Thanks for working on this Mike! 😄

Yeah that's ok. `ucx-py` does is agnostic to CPU/GPU. Only `ucx` needs to be built for CPU and GPU versions explicitly.

Looking at the logs thus far looks ok to me. Though please let me know if there were other concerns I'm missing.

**Comment by quasiben** [comment]
@mike-wendt I think we are good here as well.  These lines show we have everything we ned

> anaconda upload /opt/conda/conda-bld/linux-64/ucx-1.8.0+gf6ec8d4-hcebc08b_20.tar.bz2
anaconda upload /opt/conda/conda-bld/linux-64/ucx-proc-1.0.0-cpu.tar.bz2

We. would be installing with something like:
> conda create -n ucx -c conda-forge -c rapidsai \
  ucx-proc=*=cpu ucx ucx-py python=3.7

**Pull request merged**
