### PR TITLE
Update CI for `branch-0.24`

### PR DESCRIPTION
**Pull request by Ethyling**
- Add `branch-0.24` to axis
- Remove `branch-0.22` from axis

### CODE REVIEW

**Review by pentschev — APPROVED** [review]
LGTM, thanks @Ethyling !

**Comment by Ethyling** [comment]
rerun tests

**Comment by Ethyling** [comment]
rerun tests

**Comment by Ethyling** [comment]
rerun tests

**Comment by pentschev** [comment]
@gpucibot merge

**Comment by pentschev** [comment]
@quasiben could you approve?

I think @jakirkham is on PTO this week, so we will probably need to forge-merge or remove him from reviewers' list.

**Review by quasiben — APPROVED** [review]

**Comment by Ethyling** [comment]
> @gpucibot merge

The Ops bot is not available for this repository so we have to do a manual merge

**Pull request merged**
