### PR TITLE
update to 1.12.1

### PR DESCRIPTION
**Pull request by quasiben**
closes https://github.com/rapidsai/ucx-split-feedstock/issues/80

cc @pentschev

### CODE REVIEW

**Comment by quasiben** [comment]
rerun tests

**Review by pentschev — APPROVED** [review]
LGTM, thanks @quasiben .

**Comment by pentschev** [comment]
It seems that this is failing because it's looking for `sys/auxv.h`, which is provided by `glibc-headers-2.17-*`, this change was introduced in https://github.com/openucx/ucx/pull/7909 in UCX 1.12.1 to fix some issues reported by us and we really need that to build properly. According to https://conda-forge.org/docs/maintainer/knowledge_base.html#using-centos-7 we should be able to use glibc 2.17 adding those changes. Could we try that @quasiben ?

**Comment by quasiben** [comment]
Yes, I can try that.  It's odd that the conda-forge version didn't require that inclusion.  Also, do you think we should also add the patch in the PR John listed above ?
https://github.com/conda-forge/ucx-split-feedstock/pull/92/files

**Comment by pentschev** [comment]
> Yes, I can try that. It's odd that the conda-forge version didn't require that inclusion. Also, do you think we should also add the patch in the PR John listed above ? https://github.com/conda-forge/ucx-split-feedstock/pull/92/files

Hmm, I actually overlooked that originally. My testing was done without that patch where I confirmed having `#define HAVE_DECL_GETAUXVAL 1`. That has anyway been fixed in https://github.com/openucx/ucx/commit/1540181cee911d6f79fbb080b6f35d59785e6b19 (will be available in 1.13.0), so assuming glibc 2.17 indeed resolves the issue, I think the patch is unnecessary.

**Comment by pentschev** [comment]
I'm not sure what the build errors mean:

<details>

```python
Solving environment: ...working... WARNING conda.models.version:get_matcher(535): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.*, but conda is ignoring the .* and treating it as 1
WARNING conda.models.version:get_matcher(535): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING conda.models.version:get_matcher(535): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.*, but conda is ignoring the .* and treating it as 3
failed
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 488, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 477, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 3088, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 2051, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/opt/conda/lib/python3.9/site-packages/conda_build/render.py", line 788, in expand_outputs
    for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/opt/conda/lib/python3.9/site-packages/conda_build/metadata.py", line 2120, in get_output_metadata_set
    conda_packages = finalize_outputs_pass(ref_metadata, conda_packages, pass_no=0,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/metadata.py", line 781, in finalize_outputs_pass
    fm = finalize_metadata(om, parent_metadata=parent_metadata,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/render.py", line 546, in finalize_metadata
    build_unsat, host_unsat = add_upstream_pins(m,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/render.py", line 386, in add_upstream_pins
    build_deps, build_unsat, extra_run_specs_from_build = _read_upstream_pin_files(m, 'build',
  File "/opt/conda/lib/python3.9/site-packages/conda_build/render.py", line 373, in _read_upstream_pin_files
    deps, actions, unsat = get_env_dependencies(m, env, m.config.variant,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/render.py", line 138, in get_env_dependencies
    actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/environ.py", line 799, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/opt/conda/lib/python3.9/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/conda/plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/opt/conda/lib/python3.9/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/opt/conda/lib/python3.9/site-packages/conda/core/solve.py", line 195, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/opt/conda/lib/python3.9/site-packages/conda/core/solve.py", line 313, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/opt/conda/lib/python3.9/site-packages/conda/core/solve.py", line 707, in _add_specs
    conflicts = ssc.r.get_conflicting_specs(tuple(MatchSpec(_)
  File "/opt/conda/lib/python3.9/site-packages/conda/resolve.py", line 1109, in get_conflicting_specs
    C = r2.gen_clauses()
  File "/opt/conda/lib/python3.9/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/conda/resolve.py", line 912, in gen_clauses
    for ms in self.ms_depends(prec):
  File "/opt/conda/lib/python3.9/site-packages/conda/resolve.py", line 796, in ms_depends
    deps = [MatchSpec(d) for d in prec.combined_depends]
  File "/opt/conda/lib/python3.9/site-packages/conda/models/records.py", line 340, in combined_depends
    result = {ms.name: ms for ms in MatchSpec.merge(self.depends)}
  File "/opt/conda/lib/python3.9/site-packages/conda/models/match_spec.py", line 478, in merge
    reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
  File "/opt/conda/lib/python3.9/site-packages/conda/models/match_spec.py", line 478, in <lambda>
    reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
  File "/opt/conda/lib/python3.9/site-packages/conda/models/match_spec.py", line 509, in _merge
    final = this_component.merge(that_component)
  File "/opt/conda/lib/python3.9/site-packages/conda/models/match_spec.py", line 760, in merge
    raise ValueError("Incompatible component merge:\n  - %r\n  - %r"
ValueError: Incompatible component merge:
  - 'mpi_mpich_*'
  - 'mpi_mpich_tempest*'
```

</details>

Seems like it fails while trying to satisfy mpich, which we don't use/depend upon. Any ideas @quasiben @jakirkham ?

**Comment by quasiben** [comment]
closing in favor of conda-forge package :)

**Comment by jakirkham** [comment]
Thanks all! 😄

Adding the `ucx-py` recipe to the `ucx-py` repo with PR ( https://github.com/rapidsai/ucx-py/pull/843 ).

**Pull request closed without merging**
