### PR TITLE
[WIP] numactl hasn't gone through aarch64 migration yet, and isn't actually needed for aarch64 compilation

### PR DESCRIPTION
**Pull request by JasonAtNvidia**
adding flags to remove need for numactl for aarch64 building

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jakirkham** [comment]
Would prefer that we actually just fix this issue. Especially since it is pretty simple to do. Could you please take a look at adding CentOS 7 CDTs?

https://github.com/conda-forge/cdt-builds

**Comment by JasonAtNvidia** [comment]
I will look into numa in the cdts.  I do see that it is specifically excluded in the cdt_slugs.yaml file, so there may be a reason.  I will revert this PR to WIP and consider deleting it soon.

**Comment by jakirkham** [comment]
Adding them in PR ( https://github.com/conda-forge/cdt-builds/pull/38 ).

**Comment by JasonAtNvidia** [comment]
Thank you @jakirkham , I couldn't get it to work in a few short hours I had to dedicate to it a couple of weeks ago.  Thank you for figuring it out, hopefully that makes it just a couple of days away from being on conda-forge naturally.

**Comment by jakirkham** [comment]
Yeah no worries.

Actually those packages are already up on conda-forge. It was merged earlier today.

**Comment by jakirkham** [comment]
Would be good if you can check that the CDT issue is resolved for you, Jason. FWIW this seems to work for me on `x86_64` CentOS 7 builds. Though that doesn't mean we are not still missing something for ARM.

**Pull request closed without merging**
