### PR TITLE
Setup CI for branch-22.06

### PR DESCRIPTION
**Pull request by Ethyling**

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]
LGTM. Thanks Jordan! 😀

**Comment by jakirkham** [comment]
rerun tests

**Review by pentschev — APPROVED** [review]

**Comment by jakirkham** [comment]
May need to add some `skip` lines here

https://github.com/rapidsai/ucx-split-feedstock/blob/d9298e209c51299dcbe73b6b8ebb4cdb2bd1b350/recipe/meta.yaml#L33

**Comment by Ethyling** [comment]
> May need to add some `skip` lines here
> 
> https://github.com/rapidsai/ucx-split-feedstock/blob/d9298e209c51299dcbe73b6b8ebb4cdb2bd1b350/recipe/meta.yaml#L33

I think these lines are coming from the upstream recipes. We were not using the CUDA versions to build

**Pull request merged**
