### PR TITLE
ENH Add CUDA 11.2 support

### PR DESCRIPTION
**Pull request by mike-wendt**
Updates build axis with CUDA 11.2 support

### CODE REVIEW

**Comment by quasiben** [comment]
We'll also need to add `ci_support/linux_64_cuda_compiler_version11.2.yaml` for this to build -- very exciting to see 11.2!

**Comment by jakirkham** [comment]
That gets added by re-rendering. So we shouldn't need to do that manually

**Comment by jakirkham** [comment]
Trying to sort out re-render issues in PR ( https://github.com/conda-forge/ucx-split-feedstock/pull/87 )

**Comment by jakirkham** [comment]
Ok I've hacked together a custom migrator that should get us unstuck here. We should be able to drop it after we drop CUDA 10.1. Please let us know if there's anything else needed here 🙂

**Pull request merged**
